"""
GitHub Issue Notifier — Shared Module
======================================
Auto-creates GitHub Issues for CSPM security events.
Used by both the remediation and IAM audit Lambdas.
"""

import json
import os
import logging
import urllib3

logger = logging.getLogger(__name__)

GITHUB_TOKEN: str = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO: str = os.environ.get("GITHUB_REPO", "")  # e.g., "username/repo-name"

http = urllib3.PoolManager()

# Label colors for auto-creation
LABELS = {
    "cspm": "0075ca",
    "security": "e11d48",
    "auto-remediated": "2da44e",
    "needs-attention": "d93f0b",
    "s3-public-access": "f59e0b",
    "s3-encryption": "8b5cf6",
    "iam-audit": "ec4899",
}

SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🟢",
}


def create_github_issue(
    title: str,
    vulnerability_type: str,
    resource_name: str,
    account_id: str,
    region: str,
    status: str,
    severity: str = "HIGH",
    details: str = "",
) -> bool:
    """
    Create a GitHub Issue for a CSPM security finding.

    Returns True if successful, False otherwise.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        logger.warning("GITHUB_TOKEN or GITHUB_REPO not set — skipping Issue creation.")
        return False

    emoji = SEVERITY_EMOJI.get(severity, "⚪")
    status_emoji = "✅" if "REMEDIATED" in status else "❌" if "FAILED" in status else "ℹ️"

    body = f"""## {emoji} {vulnerability_type} — Severity: {severity}

| Field | Value |
|-------|-------|
| **Resource** | `{resource_name}` |
| **Account** | `{account_id}` |
| **Region** | `{region}` |
| **Status** | {status_emoji} **{status}** |
| **Severity** | {emoji} {severity} |

### Details
{details or "Detected and processed by CSPM automated pipeline."}

---
*Auto-generated by Serverless CSPM • Automated Security Posture Management*
"""

    labels = ["cspm", "security"]
    if "REMEDIATED" in status:
        labels.append("auto-remediated")
    else:
        labels.append("needs-attention")

    # Add type-specific label
    type_label_map = {
        "S3 Public Access": "s3-public-access",
        "S3 Encryption": "s3-encryption",
        "IAM Audit": "iam-audit",
    }
    if vulnerability_type in type_label_map:
        labels.append(type_label_map[vulnerability_type])

    payload = json.dumps({
        "title": title,
        "body": body,
        "labels": labels,
    }).encode("utf-8")

    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"

    try:
        response = http.request(
            "POST",
            url,
            body=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"token {GITHUB_TOKEN}",
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "CSPM-Bot",
            },
        )
        if response.status in (200, 201):
            data = json.loads(response.data.decode("utf-8"))
            logger.info("GitHub Issue created: #%s — %s", data.get("number"), data.get("html_url"))
            return True
        else:
            logger.warning(
                "GitHub API returned %s: %s",
                response.status,
                response.data.decode("utf-8", errors="replace")[:300],
            )
            return False

    except Exception as exc:
        logger.error("Failed to create GitHub Issue: %s", exc)
        return False
