id: prowler-aws-ec2_securitygroup_allow_ingress_from_internet_to_port_3389
name: SG Open RDP
provider: aws
service: ec2
severity: MEDIUM
description: 'Prowler: SG Open RDP'
enabled: true
check: prowler_ec2_securitygroup_allow_ingress_from_internet_to_port_3389
remediation: ''
auto_remediate: false
compliance:
- framework: Prowler
  control: ec2_securitygroup_allow_ingress_from_internet_to_port_3389
feed_source: prowler
prowler_check: ec2_securitygroup_allow_ingress_from_internet_to_port_3389
synced_at: '2026-03-21T17:55:20.092404+00:00'
